// function imports
import { getOAuthAccessToken } from "./services/authentication";
import {
  attachStorage,
  cloneServer,
  createServer,
  deleteServer,
  getDiskUsage,
  getServersList,
  restartServer,
  scaleStorage,
  scaleVolumeSize,
  setAutoscalePolicy,
  startServer,
  stopServer,
  updateServerLabel,
  upgradeServer,
} from "./services/server";

//types imports
import {
  AttachStorageParameters,
  AttachStorageResponse,
  CloneServerParameters,
  CloneServerResponse,
  CreateServerParameters,
  CreateServerResponse,
  DeleteServerParameters,
  DeleteServerResponse,
  DiskUsageResponse,
  GetServersListResponse,
  RestartServerParameters,
  RestartServerResponse,
  ScaleStorageParameters,
  ScaleStorageResponse,
  ScaleVolumeSizeParameters,
  ScaleVolumeSizeResponse,
  SetAutoscalePolicyParameters,
  StartServerParameters,
  StartServerResponse,
  StopServerParameters,
  StopServerResponse,
  UpdateServerLabelParameters,
  UpdateServerLabelResponse,
  UpgradeServerParameters,
  UpgradeServerResponse,
} from "./types/server";
import {
  GetOAuthAccessTokenRequest,
  GetOAuthAccessTokenResponse,
} from "./types/authentication";

export {
  // function exports
  getOAuthAccessToken,
  attachStorage,
  cloneServer,
  createServer,
  deleteServer,
  getDiskUsage,
  getServersList,
  restartServer,
  scaleStorage,
  scaleVolumeSize,
  setAutoscalePolicy,
  startServer,
  stopServer,
  updateServerLabel,
  upgradeServer,

  //types exports
  AttachStorageParameters,
  AttachStorageResponse,
  CloneServerParameters,
  CloneServerResponse,
  CreateServerParameters,
  CreateServerResponse,
  DeleteServerParameters,
  DeleteServerResponse,
  DiskUsageResponse,
  GetServersListResponse,
  RestartServerParameters,
  RestartServerResponse,
  ScaleStorageParameters,
  ScaleStorageResponse,
  ScaleVolumeSizeParameters,
  ScaleVolumeSizeResponse,
  SetAutoscalePolicyParameters,
  StartServerParameters,
  StartServerResponse,
  StopServerParameters,
  StopServerResponse,
  UpdateServerLabelParameters,
  UpdateServerLabelResponse,
  UpgradeServerParameters,
  UpgradeServerResponse,
  GetOAuthAccessTokenRequest,
  GetOAuthAccessTokenResponse,
};
